version: '3.8'

services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: cs_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    environment:
      TZ: Australia/Melbourne

  nginx:
    image: nginx:alpine
    container_name: cs_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    environment:
      TZ: Australia/Melbourne

  mysql:
    image: mysql:8.0
    container_name: cs_mysql
    restart: always
    command: >
      sh -c "mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p$$MYSQL_ROOT_PASSWORD mysql 
      & exec mysqld --default-time-zone='Australia/Melbourne'"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sms
      MYSQL_USER: sms_user
      MYSQL_PASSWORD: sms_pass
      TZ: Australia/Melbourne
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
